import type { Product } from "@/types";

// Dữ liệu mẫu sản phẩm theo category - gộp từ sampleData.ts và loại bỏ trùng lặp
export const sampleProducts: Record<string, Product[]> = {
  "thit-ca-trung-hai-san": [
    {
      id: 1,
      name: "Má đùi gà cắt sẵn",
      description: "Má đùi gà tươi ngon, đã cắt sẵn",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/Category/Images/8781/thit-heo_202509110924556310.png",
      unit_price: 46000,
      final_price: 41582,
      stock_quantity: 50,
      discount_percent: 10,
      is_hot: true,
      slug: "ma-dui-ga-cat-san",
      quantity: "500g",
    },
    {
      id: 2,
      name: "Sườn que heo nhập khẩu",
      description: "Sườn que heo nhập khẩu tươi ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/Category/Images/8781/thit-heo_202509110924556310.png",
      unit_price: 42000,
      final_price: 38000,
      stock_quantity: 30,
      discount_percent: 10,
      is_hot: false,
      slug: "suon-que-heo-nhap-khau",
      quantity: "500g",
    },
    {
      id: 3,
      name: "Sườn cốt lết C.P",
      description: "Sườn cốt lết C.P tươi ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/Category/Images/8781/thit-heo_202509110924556310.png",
      unit_price: 44700,
      final_price: 37530,
      stock_quantity: 25,
      discount_percent: 10,
      is_hot: true,
      slug: "suon-cot-let-cp",
      quantity: "300g",
    },
    {
      id: 4,
      name: "Đầu cá hồi salar làm sạch",
      description: "Đầu cá hồi salar nhập khẩu đã làm sạch",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/Category/Images/8781/thit-heo_202509110924556310.png",
      unit_price: 98000,
      final_price: 49000,
      stock_quantity: 15,
      discount_percent: 50,
      is_hot: false,
      slug: "dau-ca-hoi-salar-lam-sach",
      quantity: "500g",
    },
    {
      id: 5,
      name: "Thịt heo xay C.P",
      description: "Thịt heo xay C.P tươi ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/Category/Images/8781/thit-heo_202509110924556310.png",
      unit_price: 35000,
      final_price: 28000,
      stock_quantity: 40,
      discount_percent: 20,
      is_hot: true,
      slug: "thit-heo-xay-cp",
      quantity: "200g",
    },
  ],
  "rau-cu-nam-trai-cay": [
    {
      id: 6,
      name: "Quýt Úc",
      description: "Quýt Úc nhập khẩu tươi ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/rau-la_202509272336201019.gif",
      unit_price: 81900,
      final_price: 69000,
      stock_quantity: 100,
      discount_percent: 16,
      is_hot: false,
      slug: "quyt-uc",
      quantity: "800g",
    },
    {
      id: 7,
      name: "Chuối già giống Nam Mỹ",
      description: "Chuối già giống Nam Mỹ tươi ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/rau-la_202509272336201019.gif",
      unit_price: 30000,
      final_price: 24000,
      stock_quantity: 80,
      discount_percent: 20,
      is_hot: false,
      slug: "chuoi-gia-giong-nam-my",
      quantity: "1kg",
    },
    {
      id: 8,
      name: "Dưa lưới tròn ruột cam",
      description: "Dưa lưới tròn ruột cam tươi ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/rau-la_202509272336201019.gif",
      unit_price: 65000,
      final_price: 53300,
      stock_quantity: 60,
      discount_percent: 18,
      is_hot: true,
      slug: "dua-luoi-tron-ruot-cam",
      quantity: "1.3kg",
    },
    {
      id: 9,
      name: "Táo Gala mini nhập khẩu",
      description: "Táo Gala mini nhập khẩu tươi ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/rau-la_202509272336201019.gif",
      unit_price: 35000,
      final_price: 27000,
      stock_quantity: 45,
      discount_percent: 23,
      is_hot: false,
      slug: "tao-gala-mini-nhap-khau",
      quantity: "400g",
    },
    {
      id: 10,
      name: "Táo Nam Phi giòn ngọt",
      description: "Táo Nam Phi giòn ngọt nhập khẩu",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/rau-la_202509272336201019.gif",
      unit_price: 55000,
      final_price: 45000,
      stock_quantity: 35,
      discount_percent: 18,
      is_hot: true,
      slug: "tao-nam-phi-gion-ngot",
      quantity: "1kg",
    },
  ],
  "dau-an-nuoc-cham-gia-vi": [
    {
      id: 11,
      name: "Dầu ăn Neptune",
      description: "Dầu ăn Neptune tinh luyện cao cấp",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/dau-an-final_202510031117342125.gif",
      unit_price: 85000,
      final_price: 75000,
      stock_quantity: 200,
      discount_percent: 12,
      is_hot: true,
      slug: "dau-an-neptune",
      quantity: "1 chai",
    },
    {
      id: 12,
      name: "Dầu ăn Simply",
      description: "Dầu ăn Simply tinh luyện cao cấp",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/dau-an-final_202510031117342125.gif",
      unit_price: 95000,
      final_price: 85000,
      stock_quantity: 150,
      discount_percent: 11,
      is_hot: false,
      slug: "dau-an-simply",
      quantity: "1 chai",
    },
    {
      id: 13,
      name: "Dầu ăn Tường An",
      description: "Dầu ăn Tường An tinh luyện cao cấp",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/dau-an-final_202510031117342125.gif",
      unit_price: 78000,
      final_price: 70000,
      stock_quantity: 180,
      discount_percent: 10,
      is_hot: false,
      slug: "dau-an-tuong-an",
      quantity: "1 chai",
    },
    {
      id: 14,
      name: "Nước mắm Phú Quốc",
      description: "Nước mắm Phú Quốc đặc sản",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/dau-an-final_202510031117342125.gif",
      unit_price: 45000,
      final_price: 40000,
      stock_quantity: 120,
      discount_percent: 11,
      is_hot: true,
      slug: "nuoc-mam-phu-quoc",
      quantity: "500ml",
    },
    {
      id: 15,
      name: "Tương ớt Chin-su",
      description: "Tương ớt Chin-su cay nồng",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/dau-an-final_202510031117342125.gif",
      unit_price: 25000,
      final_price: 22000,
      stock_quantity: 300,
      discount_percent: 12,
      is_hot: false,
      slug: "tuong-ot-chin-su",
      quantity: "250g",
    },
  ],
  "mi-mien-chao-pho": [
    {
      id: 16,
      name: "Gấu Đỏ - Mì ăn liền",
      description: "Mì ăn liền Gấu Đỏ vị tôm chua cay thơm ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/gau-do_202510031119471876.gif",
      unit_price: 96000,
      final_price: 86000,
      stock_quantity: 150,
      discount_percent: 10,
      is_hot: true,
      slug: "gau-do-mi-an-lien",
      quantity: "1 thùng",
    },
    {
      id: 17,
      name: "Hảo Hảo - Mì tôm",
      description: "Mì tôm Hảo Hảo vị chua cay đậm đà",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/gau-do_202510031119471876.gif",
      unit_price: 50000,
      final_price: 45000,
      stock_quantity: 200,
      discount_percent: 10,
      is_hot: false,
      slug: "hao-hao-mi-tom",
      quantity: "1 gói",
    },
    {
      id: 18,
      name: "Kokomi - Mì lẩu",
      description: "Mì lẩu Kokomi vị tôm chua cay thơm ngon",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/gau-do_202510031119471876.gif",
      unit_price: 58000,
      final_price: 52000,
      stock_quantity: 80,
      discount_percent: 10,
      is_hot: true,
      slug: "kokomi-mi-lau",
      quantity: "1 gói",
    },
    {
      id: 19,
      name: "Omachi - Mì tôm",
      description: "Mì tôm Omachi vị chua cay đặc biệt",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/gau-do_202510031119471876.gif",
      unit_price: 42000,
      final_price: 38000,
      stock_quantity: 120,
      discount_percent: 10,
      is_hot: false,
      slug: "omachi-mi-tom",
      quantity: "1 gói",
    },
    {
      id: 20,
      name: "Acecook - Mì gói",
      description: "Mì gói Acecook vị tôm chua cay",
      image_url:
        "https://cdnv2.tgdd.vn/bhx-static/bhx/menuheader/gau-do_202510031119471876.gif",
      unit_price: 35000,
      final_price: 32000,
      stock_quantity: 300,
      discount_percent: 9,
      is_hot: false,
      slug: "acecook-mi-goi",
      quantity: "1 gói",
    },
  ],
};